export default interface Product{
    hsnCode:'',
    Product: '',
    ProductCategory: '',
    uom: '',
    binLocation: '',
    unitPrice: '',
    landingChargesPercent: '',
    landingCharges: '',
    costOfProduct: '',
    profitPercent: '',
    targetedSellingPrice: '',
    gstApplicable: '',
    igstPercent: '',
    cgstPercent: '',
    sgstPercent: '',
    stockKeepingUnit: '',
    latestUnitPrice: '',
    latestPODate: '',
    latestPONumber: '',
    openingStock: '',
    currentQuantity: '',
    thresholdQuantity: '',
    stockLevelAlert: '',
    productDescription: '',
    productImage: null

}